// AUTO-GENERATED by scripts/make-logo-data.py — do not edit by hand.
// 开屏动画的两个 LOGO 素材:144x144 PNG 字节(base64)。
// 宿主要求真实图片文件字节;裸灰度数组会 sendFailed(实测)。

export const LOGO_SIZE = 144

/** 插件自己的 He 图标(原始 96px,居中于 144 画布) */
/** Hermes 桌面端黑白头像(已去斑、裁边顶格) */
export const LOGO_PORTRAIT_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAAAAADCLb1kAAALqUlEQVR4nO1c6XGlOhY+PTUJaELQC0EdghwCDkEOAYegGwIO' +
  'gRuCbggiBAhBhKApLYAAbWD31Lyqd3642yDg09l0FskA/9DfjH7lbkri/zPPADOeyIDm5ZKlgQAMGNn/T4DnGc/zMmIAsE8g' +
  'tA6t+WjyHm9weTrfoF/Xrks/7T9Jv6qvsgb/We4sNP8HagDd485s9MzQojRVdP78v48Xevok15BMlmBaLiCEMSF1s9InSMff' +
  'BboCZx5eryF+C1NKqgT/K/urxHO1+szP5wCIYMOLaRrOwFDT0OuIdqSFriXBMGr6cbswdhHekr7iVWk8qhpOb6aOCcaYNFyu' +
  'V29CSvKnktSRF6RbptJFVLkZbyKqhoPPz+LO3x0jTELdLURC3YZjiC6Ca+BMTfHd52dUeRpa6z5jg9yPaSP3sLyMqPiE1lrm' +
  'rbjJIEIl3T4xqCwwFfvQjqhKSw2uIarQH1HhMbF/D/k2ojKetgxn49EYXcjEDwIaa9aAQI+6yC2E8g4p8pokyfr4yNtaZAIt' +
  'JtUsKvjSviaUQAC4Wc01IjQmV89QAsTygPoq1mBOR8MYktI5KqBWaPx7eJDFY1SWE7RYkzqwiABTqKAbdU5RFuVFm2VS1ArO' +
  'PcdDyL3UUoylT63jc4NUWZ/xiIGpbWzAIh9fO4zSgK8B1OYGUSeRUDonkene+RjHTOS1iJlfGDZOkm2uo4ZFuWW1gzDIph6Q' +
  'UZWNQURpguU4CvvFTvqPSmjbVvWMsU5zLpQFmNeiMqARocDHkWWRYkiMovO/CaW02LiHGmQZojXBhI3S2F8PgBazyxlaeUiD' +
  'ZN8L6vWoR9wygQj3DAHU9+LsCAO1RusSuKRrOQXxQ9MDBAhBV0XiHGndsaZVo+MqWxZTx6KNvHOMKdyC9h4gTBQ2vOg7AMQ1' +
  'cgog5Qi4FUK0IA2ivhXMKcjBscVTvP4+IAGCUa2k1g1tMRNAR844AdgEhLueIugO6TM9u6KNmvuAKPRYKkb1CCbvoQmzBzj6' +
  'Ki9K43jOhNRdQFYHCAIq2tMnC+S9TfyptFXHig0BfZkfA8DrZepjl2gg0zQNCYY+9wp3phTebxSJ2tY57YsyA4B/pV86XOTK' +
  '7tmXrxbFaH5lnswAet7HA5M1O5RAlQOU0aFE4cdT6mOOpuzdHCBDcXkeI6wDXSuzHSi15GdFNmQnCd+qi2aYnwZUUOmpNjG6' +
  'KLPbgIZdTPR/wCGYSu4t9+x0x+wL9Gz+CIvuA5qmunT/hkuJm2C0phISVvdNP5F8XOYQCm19+rwvs7yCxtFGBdLumHKp6r+n' +
  'eByfBRSrqAASFoNdqJgIg9SL3IrHsdm1LDF78QmEvg/QYgRP4BOeMYJ5AjQMU34F29GQU9HaHJq0vnTcAemcF0K7pEbVe+94' +
  'YJ0FdFYittzhTK0TJGFAWu8r8Q1Au7QKMUGCRTq812z6wL6p1XlAOxZhk9SsDQRTIt4yH+yz1yMg1LC0DMUNQDstarhpjK08' +
  'wuCL+g6WjABqpRTSFSAixG8AOhUK0aZGfeNzgNbUYLg6A0LMPE3bK1pdAqRtpcBWeDyFdVT3dTEGMC/oELkFSI/Gmlq6uuX1' +
  'NaNQo0FLBQ4WpuL6FzBwvAVI2y5ha2ZO2pDRLSYtJ8Rwz1bzHF2JIsVNQFoLRo0yIVONDZyO5wYNF4ErcXZMq31LONOF9TT9' +
  'ZcA8XzgsyQ4TzAiFTJn/ql87TNk61aAucEibuoxT7kJDJ16hSlAsob4WD01DW1DaS7n3HB9dB2iyP9t4AeomoEQuVAdoNj8Y' +
  '/16kXDf6Aodo3bD/CaDZKOHnDMPzBwHFk7N6DvH5A+b3t8tfuKhE9Ryi4vlBRS50nn4qwy+6IWVgjLov+KGi0hejxloOzc4B' +
  'N/j5g0aWEHEVoGn5gX4UUFRmdRwC+7mvfMHjQhL0Q4AmeCzS+xlAsSJdrnC+fcoBIvB8wHBIpw+jLtE0kXtW1thhcgl32jFa' +
  '+b5RwDo2GWoBUTuMObs2sVq0jHqj8tDcBITXXi9BQknTgi+UkStLD0sD8CIg5V/fjcCNaxTRrDPsRdEit/wr5S1AcpmPpkCJ' +
  'qtgAYZp8eSIkFlhXmv20/PsQdOApaYRGVq6Hzk3Gl5Y4xJeBWOl0NzAIb0lFguaW6YMSZTj0+RGZ+/SV0daAQzX5oktXzstZ' +
  'AtDjEWjBsF1OO+PAhaOmoiOak1lMjXHcnllNCkRrIpFORV6Y5NAj5PoUsOUruaIHgxh82XZtTYm5TmTTMyx5DuGtz9T7tzcj' +
  '9PZRXtdmJ9bBKGYR0HPnaofwlulQl+i9YgxgN+d5Qh9fRUB7ubx2v30k9HrjSSZCCWiZ8YTYx1AU2Q7dtL/35h+fh+fj/ffv' +
  'R/RzrHqlnYDt9CAaD80ArzUtfB5uDr8JmdE0e10f5rNFoa7ZzTpGi2OYAePX9jVLJxPGQUagii7F1c75fot5ye6RWoMa3axh' +
  'SAbQuu+orexbrK0R3Kf3oWxElpkyA34pzSR0yCrNw+n+M64jO7JGjvf7wkp2jwPdRDDvBZyIRRsxyrrcz1Q9neNdYpziZlW+' +
  'fIXZcpgPQ1KALjfmurCbhaUsr65ymQCzkRQrADohQnkzRupiGo3WlKCxBkCzOhQ5jsPyzm5+Sy4pcWrWBQMf9C0KKGisOOqL' +
  '2wrgGtH35X8o8vA5knB9ipX6mvJqd6Frbjde+3fbwGUTWQyQJoCD9JTKwkYZSzyxEb9E0vrQJg+IG/fWmf2diDCha/rzPNU2' +
  'LhBWNsFs84AsR5jUyp722E67pFnAtOxuJdONK8r3eUB+rrQTUrjdr242SU4xc2xqvIOocxn4WAAUT2NYaltlZ5Yu22+6jEhZ' +
  'Bi1drzSgGCISdX6oE2NH284v2bEDZhmirm7Ay4DOc0Wxo2OW6cbeaYtcB2xcNoFXkXAFlbEC0PF8H5KRdpK9oZZGb7j1PTbw' +
  'jJS4dte6GyELyDR60fooXctVJ2pMAckqvHnxtsXgCABT1ysNyJ0t3BpVxQbe/HoHgmZMCIW3ZC4h6PAb9cPX1PTwWjIgxOaX' +
  'LdyaM7honoZhAszQI1yDKLLxsd+2UdXAU8gfiMqdViLKiIkq4Y+gmYWhlfYrqN1qSUay1B7/XFhIj2W0im37xGw1F8LttU0R' +
  'N3rdau3OLzKJsbQtayD7V3NjlCyz2ariuBvPAVmnqvpm9HCIVIgqt/qdzkqaQPKw/SKGJwdI7VU5waluWWDMCVJM/VORyoSx' +
  '1N1fFtiVPderOZmN4eN9gmHUHzY1CRDF3q1GKyVmUdo81eEE7PadDCC9qTPu8415mwBxGN1SmKjcGD3CiTPC26tygLQWLaWU' +
  'sl7lT3bZWrE58WGdS/JUUrNEDfS4t+HGqW2aAtMA8SdgsOMPKWrl+QRM+MI6PH0EivXHbPTLIwNpUdvjKQkSie06u9eWD3zr' +
  'RJpvt8gsI1poXCSbPbTVxPV299q2RmhNjEFhbbczSAwD8ueuxwpANUeleUJ/0PKssLxqC8fsfDxw2hxzfO14UYEIWiLaZa7G' +
  'Owur+KXZSaDhH1eI4ikKrdvD6fslol2n6o+UhjuuUoTPQ+AiIr4by7RG5HDEz4zo7Ea68sl9c1CthGfbaleFpwXu1tJlhPSR' +
  'VldjsmOic1d92pvv5WX0Be+jYesSjCBYxicmKY4njYifhrV+6976hJUft8DaH8OTOqPcw5lBwHfjnfcdreTEz+ExDefz+PEQ' +
  'A3HrkXebCJ0PN7LaCpg/gsfEn6f3kcMQaS3JlI7Xoc7gjKxohdFfwWOCApV30NhUmKkJa1b/5zM24WT5s3iMSHZKoJzAmpVP' +
  '1Fi2YVB/WHSNrPq6v9dxBY49yj8eGdRuaSsfwTJo44TPI5zRX1GhrZRcpG5VJWzxBLGrqc/0OIhnFqwGIbmgQvVoHCRhd3hI' +
  'N/fA8pHdrLu179coSVqDrPNCKlm1TO6OMV3pHsOEYMb9HDQYZsDoQYQ7EogAPn1y7HpEQA8FZKeCwcUZoexfg/uH/m70X7Ud' +
  'BDl4IAolAAAAAElFTkSuQmCC'

function decode(b64: string): Uint8Array {
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i)
  return out
}


export function logoPortraitBytes(): Uint8Array { return decode(LOGO_PORTRAIT_PNG_BASE64) }
